# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaseProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BaseProject

#pod 'Masonry'
#pod 'AFNetworking'
#pod 'MJRefresh'
#pod 'FMDB'
#pod 'SAMKeychain'
#pod 'IQKeyboardManager'
#pod 'WZLBadge'  # 添加小红点工具
pod 'DateTools'
#pod 'DACircularProgress' # 一个圆圈状的进度显示view
#pod 'YYText'
#pod 'ReactiveCocoa', '2.3.1'
#pod 'TZImagePickerController'  # 照片选择控件

pod 'MBProgressHUD'
pod 'YYText'
pod 'SDWebImage'

  target 'BaseProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaseProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
